### ISSUE TITLE
API login logic 

### ISSUE THREAD

**Issue by kgundula** [mtswenij/smartcitizens#3]
If you log in from the app and you are authenticated but you do not have any properties yet the JSON payload returned does not have the user model.

this was return by an authenticated log in... the user object model should have been returned.
{"properties":[]}

**Comment by ishmaelmakitla** [comment]
This is probably because the object req.user is not set. The login code should work as is because it returns the required payload. See: 
                  var user = req.user;
          user.password = "this-is-not-it";
          res.send({"user":user, "properties": properties});
Please try to reproduce this by logging in as someone who has at least one property and let me know if the properties are returned.

**Comment by kgundula** [comment]
Yes i understand that my leader but look at the code snippet below extracted from the login api call : 
  var user = req.user is only assigned inside the if condition. so when you don't have properties it won't have a user object model.....

I might be wrong but please scrutinize this logic.

 Properties.getPropertiesOfOwner(req.user.id, function (err, properties){  
        if(properties && properties.length >0){
          //render main display page
          var user = req.user;
          user.password = "this-is-not-it";
          res.send({"user":user, "properties": properties});  
        }
        else{
          res.send({"user":user, "properties": []});
        }  
    });

**Comment by ishmaelmakitla** [comment]
You are right KG, please pull the changes and let me know if it works now.
