### ISSUE TITLE
API Properties 

### ISSUE THREAD

**Issue by kgundula** [mtswenij/smartcitizens#4]
I am getting this error when i try to get lists using the following api call

: http://smartcitizen.defensivethinking.co.za/api/properties/owner/ownerId

Error: Failed to lookup view &quot;[object Object]&quot; in views directory &quot;/root/smartcitizens/views&quot;<br> &nbsp; &nbsp;at Function.app.render (/root/smartcitizens/node_modules/express/lib/application.js:516:17)<br> &nbsp; &nbsp;at ServerResponse.res.render (/root/smartcitizens/node_modules/express/lib/response.js:900:7)<br> &nbsp; &nbsp;at /root/smartcitizens/routes/index.js:339:9<br> &nbsp; &nbsp;at Promise.&lt;anonymous&gt; (/root/smartcitizens/routes/properties.js:25:9)<br> &nbsp; &nbsp;at Promise.&lt;anonymous&gt; (/root/smartcitizens/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)<br> &nbsp; &nbsp;at Promise.EventEmitter.emit (events.js:95:17)<br> &nbsp; &nbsp;at Promise.emit (/root/smartcitizens/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)<br> &nbsp; &nbsp;at Promise.fulfill (/root/smartcitizens/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)<br> &nbsp; &nbsp;at /root/smartcitizens/node_modules/mongoose/lib/query.js:1056:26<br> &nbsp; &nbsp;at model.Document.init (/root/smartcitizens/node_modules/mongoose/lib/document.js:250:11)

**Comment by ishmaelmakitla** [comment]
Called method "render" by mistake instead of res.send({}). I have made the corrections and pushed the changes up.
